### ISSUE TITLE
Please check

### ISSUE THREAD

**Issue by ajitsinghkaler** [keidakira/my-watchlist#1]
You have left firebase config keys in src/firebase,js. please remove them and from github history too
Some one can use them and it can cost you lot if money

**Comment by keidakira** [comment]
Thanks, I totally forgot about it, removed them!

**Comment by ajitsinghkaler** [comment]
Still there https://github.com/keidakira/my-watchlist/blob/main/src/firebase.js

**Comment by keidakira** [comment]
Oh yeah sorry didn't see it. Thanks a lot for noticing it!
